services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "5001:5001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=simple_bank
      - DB_SSLMODE=disable
      - DB_SOURCE=file://db/migration
      - PORT=5000
      - PORT_GATEWAY_GRPC=5001
      - GRPC_PORT=50051
      - TOKEN_SYMMETRIC_KEY=f249578459530d4130f56e7ea64f8107
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
      - ENVIROMENT=development
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - REDIS_DB=0
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  postgres_data:
