// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          int64        `json:"id"`
	UserUuid    uuid.UUID    `json:"user_uuid"`
	Owner       string       `json:"owner"`
	Currency    string       `json:"currency"`
	Balance     string       `json:"balance"`
	Status      int16        `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	AccountUuid uuid.UUID    `json:"account_uuid"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount      string       `json:"amount"`
	CreatedAt   time.Time    `json:"created_at"`
	EntriesUuid uuid.UUID    `json:"entries_uuid"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	TypeTrans   string       `json:"type_trans"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Transaction struct {
	ID              int64        `json:"id"`
	FromAccountID   int64        `json:"from_account_id"`
	ToAccountID     int64        `json:"to_account_id"`
	Amount          string       `json:"amount"`
	CreatedAt       time.Time    `json:"created_at"`
	TransactionUuid uuid.UUID    `json:"transaction_uuid"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID                int64     `json:"id"`
	UserUuid          uuid.UUID `json:"user_uuid"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Role              string    `json:"role"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	DeletedAt         time.Time `json:"deleted_at"`
}
