name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment variables
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_SSLMODE=${{ secrets.DB_SSLMODE }}" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      id: go

    - name: Run All Unit Tests
      run: make -f Makefile.github gotest
